POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization:  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhamlpODIhIiwiaWQiOiI2MmRjZjJiZDQ5OWExYTVkNTU0MGJkNDciLCJpYXQiOjE2NTg2NjMyNDQsImV4cCI6MTY1ODY2Njg0NH0.CSomsMHtIuKOdQDrW2LYhbRRrX4Q7RfhozTT3D1gl-8

{
    "title": "TEST: aajii82 blog",
    "author": "Irmeli",
    "url": "http://www.blog.com",
    "likes": 1,
    "userId": "62dcf2bd499a1a5d5540bd47"
}